import { User, Book, Review, Subscription, UserRole, SubscriptionStatus, ApprovalStatus } from './types';

export const MOCK_USERS: User[] = [
  { id: 1, name: 'Admin User', email: 'admin@example.com', role: UserRole.ADMIN, subscriptionStatus: SubscriptionStatus.ACTIVE, registeredDate: new Date('2023-01-01'), purchasedBookIds: [], wishlistBookIds: [] },
  { id: 2, name: 'Reader User', email: 'reader@example.com', role: UserRole.READER, subscriptionStatus: SubscriptionStatus.ACTIVE, registeredDate: new Date('2023-02-10'), purchasedBookIds: [4, 6, 7], wishlistBookIds: [2, 8] },
  { id: 3, name: 'Guest User', email: 'guest@example.com', role: UserRole.GUEST, subscriptionStatus: SubscriptionStatus.TRIAL, trialStartDate: new Date(), registeredDate: new Date(), purchasedBookIds: [], trialEngagement: { booksDownloaded: 1, reviewsWritten: 0, aiSummariesGenerated: 2, logins: 3 }, wishlistBookIds: [] },
  { id: 4, name: 'Author User', email: 'author@example.com', role: UserRole.AUTHOR, subscriptionStatus: SubscriptionStatus.INACTIVE, registeredDate: new Date('2023-03-15'), purchasedBookIds: [], wishlistBookIds: [] },
  { id: 5, name: 'Publisher User', email: 'publisher@example.com', role: UserRole.PUBLISHER, subscriptionStatus: SubscriptionStatus.INACTIVE, registeredDate: new Date('2023-04-20'), purchasedBookIds: [], wishlistBookIds: [] },
  { id: 7, name: 'Second Author', email: 'author2@example.com', role: UserRole.AUTHOR, subscriptionStatus: SubscriptionStatus.INACTIVE, registeredDate: new Date('2023-06-01'), purchasedBookIds: [], wishlistBookIds: [] },
];

export const MOCK_BOOKS: Book[] = [
  { 
    id: 1, 
    title: 'The Future of AI', 
    authorId: 4, 
    publisherId: 5, 
    description: 'An in-depth look at the future of artificial intelligence and its impact on society.', 
    category: 'Technology', 
    coverImage: 'https://picsum.photos/seed/book1/300/400', 
    uploadDate: new Date('2023-06-01'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['AI', 'Future', 'Tech'],
    bookFileName: 'the_future_of_ai.pdf',
    totalPages: 320,
    content: `Chapter 1: The Dawn of a New Era. The journey into artificial intelligence began not with silicon chips and complex algorithms, but with a simple, profound question: can machines think? This question, posed by pioneers like Alan Turing, set the stage for a technological revolution that would reshape our world. Early AI research was characterized by boundless optimism, with researchers believing that human-level intelligence was just around the corner. The reality, of course, was far more complex. The first wave of AI, based on symbolic reasoning, showed promise but ultimately hit a wall, unable to cope with the ambiguity and vastness of the real world. This led to the first 'AI winter,' a period of reduced funding and interest. However, the seeds of the next revolution were already being sown. The development of neural networks, inspired by the structure of the human brain, offered a new path forward. These networks could learn from data, adapting and improving over time without being explicitly programmed for every task. This marked a paradigm shift from rule-based systems to learning-based systems.`
  },
  { 
    id: 2, 
    title: 'Cosmic Journeys', 
    authorId: 4, 
    publisherId: 5, 
    description: 'A thrilling sci-fi adventure through distant galaxies and unknown worlds.', 
    category: 'Science Fiction', 
    coverImage: 'https://picsum.photos/seed/book2/300/400', 
    uploadDate: new Date('2023-06-05'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Sci-Fi', 'Space', 'Adventure'],
    price: 1099,
    bookFileName: 'cosmic_journeys.epub',
    totalPages: 450,
    content: `The starship 'Odyssey' sliced through the silent void, its destination a shimmering nebula on the edge of known space. Captain Eva Rostova stood on the bridge, her gaze fixed on the swirling colors of the celestial cloud. For years, the 'Crimson Nebula' had been a mystery, an anomaly that defied all known laws of physics. Now, she and her crew were on a mission to uncover its secrets. "Status report, Mr. Jax," Eva said, her voice calm and steady. Jax, the ship's cybernetically enhanced first officer, turned from his console. "All systems nominal, Captain. We are approaching the nebula's outer rim. Energy readings are off the charts, unlike anything we've ever encountered." The ship's science officer, Dr. Aris Thorne, chimed in, "The gravitational forces are fluctuating wildly. It's as if the very fabric of spacetime is being warped here." Eva nodded. "Prepare for the unexpected. This is what we came for."`
  },
  { 
    id: 3, 
    title: 'The Art of React', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Master the art of building modern web applications with React and TypeScript.', 
    category: 'Programming', 
    coverImage: 'https://picsum.photos/seed/book3/300/400', 
    uploadDate: new Date('2023-07-10'), 
    approvalStatus: ApprovalStatus.PENDING,
    tags: ['React', 'Web Dev', 'TypeScript'],
    bookFileName: 'the_art_of_react.pdf',
    totalPages: 550,
    content: `Introduction to Components. At the heart of every React application lies the concept of a component. A component is a self-contained, reusable piece of the user interface. Think of it like a Lego brick. You can build complex structures by combining smaller, individual bricks. Similarly, in React, you build complex user interfaces by composing simple components. There are two main types of components in React: functional components and class components. While class components were the original way to create stateful components, the introduction of Hooks has made functional components the preferred choice for modern React development. They are simpler, more concise, and easier to test. A functional component is just a JavaScript function that returns JSX, which is a syntax extension for JavaScript that looks like HTML.`
  },
  { 
    id: 4, 
    title: 'Mystery on the Orient', 
    authorId: 7, 
    publisherId: 5, 
    description: 'A classic whodunit set on a luxurious train journey across Europe.', 
    category: 'Mystery', 
    coverImage: 'https://picsum.photos/seed/book4/300/400', 
    uploadDate: new Date('2023-07-12'), 
    approvalStatus: ApprovalStatus.REJECTED,
    tags: ['Mystery', 'Thriller'],
    price: 699,
    totalPages: 280,
    content: `The snow fell in thick, silent sheets, blanketing the European countryside in a pristine layer of white. Inside the opulent carriages of the Orient Express, however, the atmosphere was anything but serene. A man had been found murdered in his compartment, stabbed a dozen times. The train was stranded, cut off from the outside world by a snowdrift. The killer was still on board. Detective Hercule Poirot, a chance passenger on this fateful journey, found himself faced with a most peculiar case. The victim was a ruthless American businessman with a dark past, and the list of potential suspects included everyone from a Russian princess to an English governess. Each passenger had a story, and each story was a lie. As Poirot began his investigation, he realized that the clues were as tangled as the web of relationships on the train.`
  },
  { 
    id: 5, 
    title: 'Gourmet Cooking Made Simple', 
    authorId: 4, 
    publisherId: 5, 
    description: 'Delicious and easy-to-follow recipes for the modern home cook.', 
    category: 'Cooking', 
    coverImage: 'https://picsum.photos/seed/book5/300/400', 
    uploadDate: new Date('2023-08-01'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Cooking', 'Recipes', 'Food'],
    price: 1599,
    totalPages: 210,
    content: `The perfect roast chicken. Achieving a perfectly roasted chicken, with crispy golden-brown skin and juicy, tender meat, is a culinary milestone for any home cook. The secret lies not in complex techniques, but in a few simple principles. First, start with a high-quality, free-range chicken. Pat the chicken dry, inside and out, with paper towels. This is crucial for getting that crispy skin. Next, season generously. Don't be shy with the salt and pepper. For extra flavor, you can stuff the cavity with aromatics like lemon, garlic, and fresh herbs like thyme or rosemary. Trussing the chicken, while not strictly necessary, helps it cook more evenly. Finally, roast it at a high temperature initially to crisp up the skin, then lower the temperature to cook it through.`
  },
  { 
    id: 6, 
    title: 'Echoes of the Forgotten City', 
    authorId: 4, 
    publisherId: 5, 
    description: 'A young historian discovers a map that leads to a legendary lost city, but she is not the only one searching for its secrets.', 
    category: 'Fiction', 
    coverImage: 'https://picsum.photos/seed/book6/300/400', 
    uploadDate: new Date('2023-08-15'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Fiction', 'Adventure', 'Lost City'],
    price: 1199,
    totalPages: 380,
    content: `Dr. Alara Vance traced the faded lines on the ancient map with a gloved finger. It was more than just a piece of parchment; it was a key. A key to the lost city of Zerzura, a place whispered about in legends for centuries, a city of untold wealth and forgotten knowledge. For years, Alara had dismissed the stories as mere folklore. But this map, discovered hidden in the binding of an old book in the dusty archives of Oxford University, was different. It was real. As she prepared for an expedition into the heart of the Sahara desert, she couldn't shake the feeling that she was being watched. A shadowy organization, known only as the 'Syndicate,' had been hunting for Zerzura for decades, and they would stop at nothing to get their hands on its secrets.`
  },
  { 
    id: 7, 
    title: 'Whispers of the Dawn', 
    authorId: 7, 
    publisherId: 5, 
    description: 'A collection of poems exploring nature, love, loss, and the quiet moments that define our lives.', 
    category: 'Poetry', 
    coverImage: 'https://picsum.photos/seed/book7/300/400', 
    uploadDate: new Date('2023-08-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Poetry', 'Nature', 'Emotions'],
    price: 799,
    totalPages: 150,
    content: `The morning mist, a gentle shroud, clings to the silent hills. A single bird, a lonely note, its morning song it spills. The sun, a timid artist's brush, paints the sky in hues of gold. A new day's story, yet untold, begins to now unfold. The dew-kissed leaves of ancient trees, a million tiny gems. Reflecting light, a fleeting sight, on fragile, verdant stems. The world awakens, soft and slow, from slumber's deep embrace. A quiet hope, a gentle flow, finds its time and place.`
  },
  { 
    id: 8, 
    title: 'My Journey Through the Stars', 
    authorId: 4, 
    publisherId: 5, 
    description: 'The autobiography of a pioneering astronaut, detailing the challenges and triumphs of a life dedicated to space exploration.', 
    category: 'Autobiography', 
    coverImage: 'https://picsum.photos/seed/book8/300/400', 
    uploadDate: new Date('2023-08-25'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Autobiography', 'Space', 'NASA'],
    price: 1449,
    totalPages: 410,
    content: `From the moment I saw the stars through my father's telescope, I knew my destiny was not on this Earth. It was a long and arduous journey from a small town in Ohio to the launchpad at Cape Canaveral. There were countless hours of study, grueling physical training, and the constant pressure to be better, faster, and smarter than the competition. But every setback, every failure, only fueled my determination. The day I finally sat in the command module of Apollo 18, I felt a mixture of terror and exhilaration. The roar of the Saturn V rocket was a force of nature, a controlled explosion that tore us away from the familiar embrace of Earth's gravity. And then, there was silence. The profound, awe-inspiring silence of space. Looking back at our planet, a tiny, fragile blue marble suspended in the vast darkness, I was overcome with a sense of wonder and humility.`
  },
  { 
    id: 9, 
    title: 'Tales from the Midnight Cafe', 
    authorId: 7, 
    publisherId: 5, 
    description: 'A collection of interconnected short stories about the peculiar patrons of a cafe that only opens after midnight.', 
    category: 'Short Stories', 
    coverImage: 'https://picsum.photos/seed/book9/300/400', 
    uploadDate: new Date('2023-09-01'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Short Stories', 'Fantasy', 'Urban'],
    price: 949,
    totalPages: 265,
    content: `The 'Midnight Cafe' wasn't on any map. You couldn't find it with a GPS. You could only find it if you were lost, truly and utterly lost, in the winding, rain-slicked streets of the city after midnight. The first tale is of a man who sold his shadow for a second chance at love. The second, of a woman who could hear the secret thoughts of cats. The third, of a time traveler who was perpetually stuck on a Tuesday. Each patron had a story, a secret, a burden they carried. And the cafe's mysterious owner, a man known only as 'The Barista,' always seemed to know exactly what they needed, whether it was a cup of coffee that tasted of forgotten memories, or a piece of advice that could change the course of their lives.`
  },
  { 
    id: 10, 
    title: 'The Wellness Blueprint', 
    authorId: 4, 
    publisherId: 5, 
    description: 'A comprehensive guide to building a healthier lifestyle, covering nutrition, exercise, and mental well-being.', 
    category: 'Health & Fitness', 
    coverImage: 'https://picsum.photos/seed/book10/300/400', 
    uploadDate: new Date('2023-09-05'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Health', 'Fitness', 'Nutrition', 'Wellness'],
    price: 1849,
    totalPages: 350,
    content: `Wellness is not a destination, but a journey. It's a holistic approach to life that encompasses physical, mental, and emotional health. This book is your blueprint for that journey. We will start with the foundation: nutrition. You will learn about macronutrients and micronutrients, how to read food labels, and how to create a balanced, sustainable eating plan that works for you. Next, we will explore the importance of movement. We will debunk common exercise myths and help you find a form of physical activity that you genuinely enjoy. Finally, we will delve into the often-neglected aspect of wellness: mental health. We will discuss stress management techniques, the importance of sleep, and the power of mindfulness and meditation.`
  },
  { 
    id: 11, 
    title: '30-Minute Vegan Dinners', 
    authorId: 4, 
    publisherId: 5, 
    description: 'Quick, easy, and delicious vegan recipes that you can get on the table in 30 minutes or less.', 
    category: 'Cooking', 
    coverImage: 'https://picsum.photos/seed/book11/300/400', 
    uploadDate: new Date('2023-09-10'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Vegan', 'Cooking', 'Recipes', 'Quick Meals'],
    price: 1449,
    totalPages: 180,
    content: `Creamy Tomato Pasta. Who says you need dairy to make a rich and creamy pasta sauce? This recipe uses cashews to create a luscious, velvety sauce that will satisfy even the most ardent cheese lover. Start by soaking raw cashews in hot water for at least 15 minutes. While the cashews are soaking, sauté some garlic and onion in olive oil until softened. Add a can of crushed tomatoes, some dried oregano, and a pinch of red pepper flakes. Simmer for 10 minutes. Drain the cashews and blend them with a little water until completely smooth. Add the cashew cream to the tomato sauce and stir until well combined. Season with salt and pepper to taste. Toss with your favorite pasta and garnish with fresh basil.`
  },
  { 
    id: 12, 
    title: 'The Simple Path to Wealth', 
    authorId: 7, 
    publisherId: 5, 
    description: 'An easy-to-understand guide to personal finance and investing for long-term financial independence.', 
    category: 'Finance', 
    coverImage: 'https://picsum.photos/seed/book12/300/400', 
    uploadDate: new Date('2023-09-15'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['Finance', 'Investing', 'Wealth'],
    price: 1600,
    totalPages: 300,
    content: `The two most powerful tools in your financial arsenal are time and compound interest. The sooner you start investing, the more time your money has to grow. And thanks to the magic of compound interest, your investment returns will start generating their own returns, creating a snowball effect that can lead to incredible wealth over time. The key is to start now, even if it's just a small amount. The path to wealth is simple: spend less than you earn, invest the surplus, and avoid debt. The best investment for most people is a low-cost, broad-market index fund. It's a simple, effective, and hands-off way to invest in the entire stock market. Don't try to time the market or pick individual stocks. Just invest consistently, month after month, and let the power of compounding do the heavy lifting.`
  },
  { 
    id: 13, 
    title: 'NCERT Mathematics Class 10', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT textbook for Class 10 Mathematics. Covers all topics as per the CBSE curriculum.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book13/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'Math', 'Class 10', 'Education'],
    totalPages: 350,
    content: `Chapter 1: Real Numbers. In this chapter, we will revisit the concept of real numbers and explore some of their important properties. We will begin with Euclid's division algorithm, which is a powerful tool for finding the HCF of two positive integers. We will then move on to the Fundamental Theorem of Arithmetic, which states that every composite number can be expressed as a product of primes in a unique way. We will also learn how to prove that numbers like the square root of 2, the square root of 3, and the square root of 5 are irrational. Finally, we will revisit the decimal expansions of rational numbers and learn how to determine whether a rational number has a terminating or non-terminating repeating decimal expansion.`
  },
  { 
    id: 14, 
    title: 'NCERT Science Class 8', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT textbook for Class 8 Science. Covers Physics, Chemistry, and Biology.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book14/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'Science', 'Class 8', 'Education'],
    totalPages: 280,
    content: `Chapter 2: Microorganisms: Friend and Foe. Microorganisms, or microbes, are tiny living organisms that are too small to be seen with the naked eye. They are found everywhere: in air, water, soil, and even inside our bodies. Some microorganisms are beneficial to us, while others are harmful and cause diseases. In this chapter, we will learn about the different types of microorganisms, such as bacteria, fungi, protozoa, and algae. We will explore the useful roles that microbes play in our lives, such as in the making of curd, bread, and alcohol. We will also learn about the harmful effects of microorganisms and the diseases they cause, such as cholera, typhoid, and malaria. Finally, we will discuss the importance of food preservation and the different methods used to prevent the spoilage of food by microbes.`
  },
  { 
    id: 15, 
    title: 'NCERT English \'Honeydew\' Class 8', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT English textbook \'Honeydew\' for Class 8.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book15/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'English', 'Class 8', 'Education'],
    totalPages: 160,
    content: `The Best Christmas Present in the World. The story begins with the author finding a roll-top desk in a junk shop. He decides to restore it and, in the process, discovers a secret drawer. Inside the drawer, he finds a small tin box containing a letter. The letter was written by a British soldier named Jim Macpherson to his wife, Connie, on Christmas Day in 1914, during the First World War. In the letter, Jim describes a remarkable event that took place on the battlefield. On Christmas morning, the British and German soldiers, who were fighting each other, declared an informal truce. They came out of their trenches, shook hands, sang carols, and even played a game of football. It was a moment of peace and humanity amidst the horrors of war. The author is deeply moved by the letter and decides to find Connie and deliver the letter to her.`
  },
  { 
    id: 16, 
    title: 'NCERT History \'Our Pasts - III\' Class 8', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT History textbook \'Our Pasts - III\' for Class 8.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book16/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'History', 'Class 8', 'Education'],
    totalPages: 220,
    content: `From Trade to Territory. The British East India Company, which was established in 1600 as a trading company, gradually transformed into a colonial power in India. The company's initial objective was to trade in spices, cotton, and silk. However, taking advantage of the political instability in India, the company started interfering in the internal affairs of the Indian states. The Battle of Plassey in 1757 was a major turning point. The victory in this battle gave the company a strong foothold in Bengal and marked the beginning of its territorial expansion in India. The company used a variety of methods, including the policy of 'divide and rule,' to expand its empire. By the mid-19th century, the British had become the dominant power in India.`
  },
  { 
    id: 17, 
    title: 'NCERT Physics Part 1 Class 12', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT textbook for Class 12 Physics, Part 1.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book17/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'Physics', 'Class 12', 'Education'],
    totalPages: 310,
    content: `Electric Charges and Fields. Electric charge is the physical property of matter that causes it to experience a force when placed in an electromagnetic field. There are two types of electric charges: positive and negative. Like charges repel each other, and unlike charges attract each other. The SI unit of electric charge is the coulomb. Coulomb's law states that the force between two point charges is directly proportional to the product of the magnitudes of the charges and inversely proportional to the square of the distance between them. An electric field is a region around a charged particle or object within which a force would be exerted on other charged particles or objects. We will also study electric dipoles and Gauss's law and its applications.`
  },
  { 
    id: 18, 
    title: 'NCERT Biology Class 12', 
    authorId: 7, 
    publisherId: 5, 
    description: 'Official NCERT textbook for Class 12 Biology.', 
    category: 'Education', 
    coverImage: 'https://picsum.photos/seed/book18/300/400', 
    uploadDate: new Date('2023-09-20'), 
    approvalStatus: ApprovalStatus.APPROVED,
    tags: ['NCERT', 'Biology', 'Class 12', 'Education'],
    totalPages: 340,
    content: `Reproduction in Organisms. Reproduction is a biological process by which new individual organisms, or 'offspring,' are produced from their 'parents.' Reproduction is a fundamental feature of all known life; each individual organism exists as the result of reproduction. There are two main types of reproduction: asexual and sexual. Asexual reproduction is a type of reproduction that does not involve the fusion of gametes or change in the number of chromosomes. The offspring that arise by asexual reproduction from a single cell or from a multicellular organism inherit the genes of that one parent. Sexual reproduction is a type of reproduction that involves a complex life cycle in which a gamete with a single set of chromosomes combines with another to produce an organism composed of cells with two sets of chromosomes.`
  }
];

export const MOCK_REVIEWS: Review[] = [
  { id: 1, bookId: 1, userId: 2, rating: 5, comment: 'A fascinating read! Highly recommend to anyone interested in AI.', reviewDate: new Date('2023-06-15') },
  { id: 3, bookId: 2, userId: 2, rating: 4, comment: 'Great story, I couldn\'t put it down!', reviewDate: new Date('2023-06-18') },
];

export const MOCK_SUBSCRIPTIONS: Subscription[] = [
  { id: 1, userId: 1, startDate: new Date('2023-01-01'), endDate: new Date('2024-01-01'), status: SubscriptionStatus.ACTIVE, plan: 'yearly' },
  { id: 2, userId: 2, startDate: new Date('2023-02-10'), endDate: new Date('2024-02-10'), status: SubscriptionStatus.ACTIVE, plan: 'yearly' },
];